version: '3.7'

services:
  localstack:
    image: localstack/localstack
    ports:
      - 4567-4599:4567-4599
      - 8080:8080
    environment:
      - SERVICES:s3:4572,kms:4599
    volumes:
      - .localstack:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock
